### ISSUE TITLE
Add Code Coverage with Codecov and Badge in README.md

### ISSUE THREAD

**Issue by skuill** [skuill/LyricsScraperNET#43]
**Description**:  
We need to integrate code coverage with Codecov to track our test coverage and display the coverage percentage in the `README.md` file.

**Tasks**:

1. **Set up Codecov integration in GitHub Actions**:
   - Add a step in the CI pipeline (GitHub Actions) to collect code coverage during test runs using `coverlet`.
   - Use `codecov-action` to upload coverage reports to Codecov.

2. **Generate and upload the coverage report**:
   - Use the `.NET Core` test framework with the `--collect:"XPlat Code Coverage"` option.
   - Save the coverage file in the `cobertura` format (XML) to be uploaded to Codecov.

3. **Add Codecov badge to `README.md`**:
   - After uploading to Codecov, add a badge to the `README.md` file that shows the percentage of code coverage.
   - Use the badge URL from the Codecov website.

4. **Set up coverage thresholds (optional)**:
   - Ensure that the CI pipeline fails if the coverage drops below a specified threshold (e.g., 80%).

---

### Steps to Implement

1. **GitHub Actions Workflow**:
   - Modify the CI pipeline to include coverage collection and upload to Codecov. Example code for your `.yml` file:

   ```yaml
   name: CI/CD LyricsScraperNET

   on:
     push:
     pull_request:

   jobs:
     lyrics_scraper_net-cicd:
       runs-on: ubuntu-20.04
       steps:
         - name: Checkout
           uses: actions/checkout@v4

         - uses: actions/setup-dotnet@v3
           with:
             dotnet-version: "7.0.x"

         - name: Restore Packages
           run: dotnet restore

         - name: Build
           run: dotnet build --configuration Release --verbosity minimal

         - name: Test with Coverage
           run: |
             dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults
           env:
             COVERLET_OUTPUT_FORMAT: cobertura

         - name: Upload Coverage to Codecov
           uses: codecov/codecov-action@v3
           with:
             files: ./TestResults/**/coverage.cobertura.xml
             token: ${{ secrets.CODECOV_TOKEN }}
             fail_ci_if_error: true
   ```

2. **Codecov Token**:
   - Create a Codecov account and generate a token for your repository.
   - Add the token as a secret in GitHub under `Settings` → `Secrets and variables` → `Actions` → `New repository secret`.

3. **Codecov Badge**:
   - After the integration is complete, go to your Codecov page for the repository.
   - Find the badge URL (typically under "Settings" → "Badges").
   - Add this URL in the `README.md` like this:

   ```markdown
   ![Code Coverage](https://codecov.io/gh/username/repository/branch/main/graph/badge.svg)
   ```
